version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: packages/client/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./packages/client:/app/packages/client
      - /app/packages/client/node_modules
    environment:
      - VITE_API_URL=http://server:3000
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./packages/server:/app/packages/server
      - /app/packages/server/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/french_pass
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=french_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: